# -*- coding: utf-8 -*-
"""soil-co2-digital-colorimetry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCmy5k0olHCt55AVQxh9IYWPNDiZltFP

# sRGB, ProPhoto RGB, and Adobe RGB values extraction from digital images
"""

from PIL import Image
import numpy as np
import colour
import matplotlib.pyplot as plt

def load_image(image_path):
    image = Image.open(image_path)
    image = image.convert('RGB')
    return image

def extract_rgb(image):
    rgb_data = np.array(image) / 255.0
    return rgb_data

def convert_rgb_space(rgb_data, target_space_name):
    target_space = colour.RGB_COLOURSPACES[target_space_name]
    converted_rgb_data = colour.RGB_to_RGB(rgb_data, colour.RGB_COLOURSPACES['sRGB'], target_space)
    return converted_rgb_data

def calculate_average_color(rgb_data, decimal_places=6):
    average_color = np.mean(rgb_data, axis=(0, 1))
    formatted_average_color = np.round(average_color, decimals=decimal_places)
    return formatted_average_color

def display_image(image):
    plt.imshow(image)
    plt.axis('off')
    plt.show()

image_path = 'file-name.jpeg'
image = load_image(image_path)
rgb_data = extract_rgb(image)

average_srgb_color = calculate_average_color(rgb_data, decimal_places=6)
print("Average sRGB color (formatted):", average_srgb_color)

adobe_rgb_data = convert_rgb_space(rgb_data, 'Adobe RGB (1998)')
average_adobe_rgb_color = calculate_average_color(adobe_rgb_data, decimal_places=6)
print("Average Adobe RGB color (formatted):", average_adobe_rgb_color)

prophoto_rgb_data = convert_rgb_space(rgb_data, 'ProPhoto RGB')
average_prophoto_rgb_color = calculate_average_color(prophoto_rgb_data, decimal_places=6)
print("Average ProPhoto RGB color (formatted):", average_prophoto_rgb_color)

display_image(image)

"""# CIELAB values extraction from digital images"""

from PIL import Image
from skimage import color
import numpy as np

def convert_to_cielab_with_normalization(image_path):
    """
    Convert an image to CIELAB color space and normalize values.

    Parameters:
    - image_path: Path to the input RGB image.

    Returns:
    - Normalized LAB image and average normalized LAB values.
    """
    image = Image.open(image_path).convert('RGB')

    image_array = np.array(image)

    lab_image = color.rgb2lab(image_array)

    lab_image[..., 0] = lab_image[..., 0] / 100.0

    lab_image[..., 1] = (lab_image[..., 1] + 128) / 255.0
    lab_image[..., 2] = (lab_image[..., 2] + 128) / 255.0

    average_normalized_lab = np.mean(lab_image, axis=(0, 1))

    return lab_image, average_normalized_lab

image_path = 'file-name.jpeg'

normalized_lab_image, average_normalized_lab = convert_to_cielab_with_normalization(image_path)

print("Average Normalized CIELAB Values (L*, a*, b*):", np.around(average_normalized_lab, decimals=10))

"""# CIE XYZ values extraction from digital images"""

import numpy as np
from PIL import Image
from skimage import color

image_path = "file-name.jpeg"
image = Image.open(image_path)

xyz_image = color.rgb2xyz(image)

average_xyz = np.mean(xyz_image, axis=(0, 1))

print("Average CIE XYZ Values:")
for channel, value in enumerate(average_xyz):
    print(f"Channel {channel}: {value:.10f}")

"""# CIECAM16 dan CIECAM02 values extraction from digital images"""

import numpy as np
from PIL import Image
import colour

image_path = 'FLOW9.jpeg'

img = Image.open(image_path).convert('RGB')
img_array = np.array(img) / 255.0

mean_rgb = np.mean(img_array, axis=(0,1))

XYZ = colour.RGB_to_XYZ(mean_rgb, 'sRGB')

xy_w = colour.CCS_ILLUMINANTS['CIE 1931 2 Degree Standard Observer']['D65']

XYZ_w = colour.xy_to_XYZ(xy_w)

L_A = 200
Y_b = 20

surround16 = colour.VIEWING_CONDITIONS_CIECAM16['Average']
cam16 = colour.XYZ_to_CIECAM16(XYZ, XYZ_w, L_A, Y_b, surround16)

h_rad16 = np.deg2rad(cam16.h)
a_M16 = cam16.M * np.cos(h_rad16)
b_M16 = cam16.M * np.sin(h_rad16)

print("Nilai CIECAM16:")
print(f"Lightness (J): {cam16.J}")
print(f"Chroma (C): {cam16.C}")
print(f"Hue angle (h): {cam16.h}")
print(f"Brightness (Q): {cam16.Q}")
print(f"Colourfulness (M): {cam16.M}")
print(f"Saturation (s): {cam16.s}")
print(f"Hue quadrature (H): {cam16.H}")
print(f"a_M (red-green opponent untuk colourfulness): {a_M16}")
print(f"b_M (yellow-blue opponent untuk colourfulness): {b_M16}")
print("\n")

surround02 = colour.VIEWING_CONDITIONS_CIECAM02['Average']
cam02 = colour.XYZ_to_CIECAM02(XYZ, XYZ_w, L_A, Y_b, surround02)

h_rad02 = np.deg2rad(cam02.h)
a_M02 = cam02.M * np.cos(h_rad02)
b_M02 = cam02.M * np.sin(h_rad02)

print("Nilai CIECAM02:")
print(f"Lightness (J): {cam02.J}")
print(f"Chroma (C): {cam02.C}")
print(f"Hue angle (h): {cam02.h}")
print(f"Brightness (Q): {cam02.Q}")
print(f"Colourfulness (M): {cam02.M}")
print(f"Saturation (s): {cam02.s}")
print(f"Hue quadrature (H): {cam02.H}")
print(f"a_M (red-green opponent untuk colourfulness): {a_M02}")
print(f"b_M (yellow-blue opponent untuk colourfulness): {b_M02}")

"""# CAM16UCS values extraction from digital images"""

import numpy as np
import matplotlib.pyplot as plt
from skimage import io, color
import cv2

def xyz_to_cam16ucs(xyz):
    """
    Approximate conversion from XYZ → CAM16-UCS using a linearized model.
    Output: array[..., 3] with J′, a′, b′
    """
    M = np.array([
        [0.7982,  0.3389, -0.1371],
        [-0.5918, 1.5512,  0.0406],
        [0.0008,  0.0239,  0.9753]
    ])

    xyz_transformed = np.dot(xyz, M.T)

    Jp = 100 * np.cbrt(np.clip(xyz_transformed[..., 1], 1e-6, None))
    ap = 175 * (xyz_transformed[..., 0] / np.clip(xyz_transformed[..., 1], 1e-6, None) - 0.3831)
    bp = 70  * (xyz_transformed[..., 2] / np.clip(xyz_transformed[..., 1], 1e-6, None) - 0.2489)

    return np.stack([Jp, ap, bp], axis=-1)

def extract_quantitative_cam16ucs(image_filename):
    image = io.imread(image_filename)

    if image.ndim == 2:
        image = color.gray2rgb(image)
    elif image.shape[2] == 4:
        image = image[..., :3]

    image = image / 255.0 if image.max() > 1.0 else image

    xyz_image = color.rgb2xyz(image)

    cam16ucs = xyz_to_cam16ucs(xyz_image)

    cam16ucs_norm = cam16ucs / np.max(cam16ucs)

    avg_values = np.mean(cam16ucs_norm, axis=(0, 1))

    print("✅ [Kuantitatif] Average normalized CAM16-UCS values:", avg_values)
    return cam16ucs_norm, avg_values

def visualize_cam16ucs(cam16ucs):
    """
    Menampilkan 3 channel (J′, a′, b′) dengan normalisasi per channel agar mudah dilihat.
    """
    channels = ['J′ (Lightness)', 'a′ (Red-Green)', 'b′ (Yellow-Blue)']
    plt.figure(figsize=(15, 4))

    for i in range(3):
        channel_img = cam16ucs[..., i]
        ch_norm = (channel_img - channel_img.min()) / (channel_img.max() - channel_img.min() + 1e-8)
        plt.subplot(1, 3, i + 1)
        plt.imshow(ch_norm, cmap='viridis')
        plt.title(channels[i])
        plt.axis('off')

    plt.suptitle("CAM16-UCS Channels Visualization", fontsize=14)
    plt.show()

image_path = "file-name.jpeg"

cam16ucs_norm, avg_values = extract_quantitative_cam16ucs(image_path)
visualize_cam16ucs(cam16ucs_norm)

"""# CAM16-SCD values extraction from digital images"""

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import colour

from colour.appearance.cam16 import InductionFactors_CAM16, XYZ_to_CAM16

image_path = "file-name.jpeg"
img = Image.open(image_path).convert("RGB")
img_np = np.asarray(img, dtype=float) / 255.0
height, width, _ = img_np.shape
rgb_flat = img_np.reshape(-1, 3)

XYZ_flat = colour.sRGB_to_XYZ(rgb_flat)

xy_w = colour.CCS_ILLUMINANTS["CIE 1931 2 Degree Standard Observer"]["D65"]
XYZ_w = colour.xy_to_XYZ(xy_w) * 100
L_A = 20.0
Y_b = 20.0
surround = InductionFactors_CAM16(F=1.0, c=0.69, N_c=1.0)

cam16 = XYZ_to_CAM16(XYZ_flat, XYZ_w, L_A, Y_b, surround)

J = cam16.J
M = cam16.M
hue_rad = np.deg2rad(cam16.h)

Jp = (1.7 * J) / (1 + 0.007 * J)
Mp = M / (1 + 0.007 * J)
ap = Mp * np.cos(hue_rad)
bp = Mp * np.sin(hue_rad)

cam16_scd_flat = np.stack([Jp, ap, bp], axis=1)
cam16_scd = cam16_scd_flat.reshape(height, width, 3)

print("✅ CAM16-SCD array shape:", cam16_scd.shape)
print("Sample pixel (J′, a′, b′):", cam16_scd[0, 0])

fig, ax = plt.subplots(1, 3, figsize=(12, 4))
for i, title in enumerate(["J′", "a′", "b′"]):
    im = ax[i].imshow(cam16_scd[..., i], cmap="viridis")
    ax[i].set_title(title)
    ax[i].axis("off")
    plt.colorbar(im, ax=ax[i], fraction=0.046, pad=0.04)
plt.tight_layout()
plt.show()

"""# CAM16-LCD values extraction from digital images"""

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import colour
from colour.appearance.cam16 import InductionFactors_CAM16, XYZ_to_CAM16

image_path = "file-name.jpeg"

img = Image.open(image_path).convert("RGB")
img_np = np.asarray(img) / 255.0
height, width, _ = img_np.shape

XYZ = colour.sRGB_to_XYZ(img_np)
XYZ_flat = XYZ.reshape(-1, 3)

XYZ_w = colour.CCS_ILLUMINANTS["CIE 1931 2 Degree Standard Observer"]["D65"]
XYZ_w = colour.xy_to_XYZ(XYZ_w)
L_A = 20
Y_b = 20
surround = InductionFactors_CAM16(F=1.0, c=0.69, N_c=1.0)

cam16 = XYZ_to_CAM16(XYZ_flat, XYZ_w, L_A, Y_b, surround)

J = cam16.J
M = cam16.M
hue = cam16.h

a = M * np.cos(np.deg2rad(hue))
b = M * np.sin(np.deg2rad(hue))

c1, c2 = 0.008, 0.0363
Jp = (1 + 100 * c1) * J / (1 + c1 * J)
Mp = (1 / c2) * np.log(1 + c2 * M)
ap = Mp * np.cos(np.deg2rad(hue))
bp = Mp * np.sin(np.deg2rad(hue))

cam16_lcd_flat = np.stack([Jp, ap, bp], axis=1)
cam16_lcd = cam16_lcd_flat.reshape(height, width, 3)

print("✅ CAM16-LCD array shape:", cam16_lcd.shape)

plt.figure(figsize=(14, 4))
for i, (title, channel) in enumerate(zip(["J′", "a′", "b′"], range(3))):
    plt.subplot(1, 3, i + 1)
    plt.imshow(cam16_lcd[..., channel], cmap="viridis")
    plt.title(f"CAM16-LCD {title}")
    plt.axis("off")
plt.tight_layout()
plt.show()

y, x = 20, 20
print("CAM16-LCD (J′, a′, b′):", cam16_lcd[y, x])

"""# CAM20u values extraction from digital images"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

Y_b = float(input("Enter background luminance (Y_b, in percentage, default=20): ") or 20)  # e.g., 20 for 20%
L_A = float(input("Enter adaptation luminance (L_A, in cd/m², default=64): ") or 64)  # e.g., 64 for indoor lighting

XYZ_D65 = [95.047, 100.0, 108.883]

def rgb_to_xyz(rgb):
    """
    Convert RGB to XYZ color space using the standard D65 illuminant.
    """
    rgb = np.asarray(rgb) / 255.0
    rgb = np.where(rgb <= 0.04045, rgb / 12.92, ((rgb + 0.055) / 1.055) ** 2.4)
    rgb = rgb.reshape(-1, 3)

    rgb_to_xyz_matrix = np.array([
        [0.4124564, 0.3575761, 0.1804375],
        [0.2126729, 0.7151522, 0.0721750],
        [0.0193339, 0.1191920, 0.9503041]
    ])
    xyz = np.dot(rgb, rgb_to_xyz_matrix.T)
    return xyz

def xyz_to_cam20u(xyz):
    """
    Convert XYZ to CAM20u color appearance model.
    """
    xyz_normalized = xyz / XYZ_D65

    X, Y, Z = xyz_normalized.T

    J = 100 * (Y / Y_b) ** (1 / 3)
    u = 13 * J * (X - 0.19783000664283)
    v = 13 * J * (Y - 0.46831999493879)

    return np.stack([J, u, v], axis=-1)

def process_image(image_file):
    """
    Load an image file, convert it to CAM20u color appearance model.
    """
    img = Image.open(image_file).convert("RGB")
    img_array = np.asarray(img)

    img_xyz = rgb_to_xyz(img_array)

    img_cam20u = xyz_to_cam20u(img_xyz)

    return img_cam20u, img_array.shape

image_file = "file-name.jpeg"

try:
    cam20u_output, img_shape = process_image(image_file)
    output_file = "cam20u_output.npy"
    np.save(output_file, cam20u_output)
    print(f"CAM20u data successfully saved to '{output_file}'")

    avg_cam20u = np.mean(cam20u_output, axis=0)
    print(f"Average CAM20u values (J, u, v): {avg_cam20u}")

    csv_output_path = "cam20u_data.csv"
    np.savetxt(csv_output_path, cam20u_output, delimiter=",", header="J,u,v", comments="")
    print(f"CAM20u data saved as CSV to '{csv_output_path}'")

    cam20u_output = cam20u_output.reshape(img_shape[0], img_shape[1], 3)
    J_channel = cam20u_output[:, :, 0]
    u_channel = cam20u_output[:, :, 1]
    v_channel = cam20u_output[:, :, 2]

    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.title("Lightness (J)")
    plt.imshow(J_channel, cmap='gray')
    plt.colorbar(label="J (Lightness)")

    plt.subplot(1, 3, 2)
    plt.title("Chromaticity (u)")
    plt.imshow(u_channel, cmap='coolwarm')
    plt.colorbar(label="u (Chromaticity)")

    plt.subplot(1, 3, 3)
    plt.title("Chromaticity (v)")
    plt.imshow(v_channel, cmap='coolwarm')
    plt.colorbar(label="v (Chromaticity)")

    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print(f"Error: File '{image_file}' not found. Please ensure the file is uploaded in the same directory.")
except Exception as e:
    print(f"An error occurred: {e}")

"""# ZCAM values extraction from digital images"""

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from colour import sRGB_to_XYZ

def calculate_zcam_values(image_path):
    try:
        image = Image.open(image_path).convert('RGB')
        image_array = np.array(image) / 255.0

        XYZ_image = sRGB_to_XYZ(image_array)

        XYZ_w = np.array([95.047, 100.0, 108.883])
        L_A = 64
        Y_b = 20

        brightness = XYZ_image[..., 1]
        chroma = np.sqrt(XYZ_image[..., 0]**2 + XYZ_image[..., 2]**2)
        hue = np.arctan2(XYZ_image[..., 2], XYZ_image[..., 0]) * (180 / np.pi)
        hue = np.mod(hue, 360)

        avg_brightness = np.mean(brightness)
        avg_chroma = np.mean(chroma)
        avg_hue = np.mean(hue)

        print("Average ZCAM Values:")
        print(f"Brightness (Y proxy): {avg_brightness:.6f}")
        print(f"Chroma: {avg_chroma:.6f}")
        print(f"Hue: {avg_hue:.6f}")

        plt.imshow(image)
        plt.axis('off')
        plt.show()

    except Exception as e:
        print("An error occurred:", e)

image_path = 'file-name.jpeg'

calculate_zcam_values(image_path)

"""# PLS to predict CO2 conc. using CAMs or color spaces data"""

import numpy as np
from sklearn.cross_decomposition import PLSRegression

x = np.array([series data of color spaces or CAMs values]).reshape(-1, 1)
y = np.array([series data of experimental conc.])

pls = PLSRegression(n_components=1)
pls.fit(x, y)

x_new = np.array([[A VALUE TO PREDICT]])
y_pred = pls.predict(x_new)

print(f'Predicted y value for x = -10.72749738: {y_pred[0]}')

"""# SVR-rbf to predict CO2 conc. using CAMs or color spaces data"""

import numpy as np
from sklearn.svm import SVR

data_x = np.array([series data of color spaces or CAMs values])
data_Y = np.array([series data of experimental conc.])

svr = SVR(kernel='rbf', C=1.0, epsilon=0.1)

data_x = data_x.reshape(-1, 1)
svr.fit(data_x, data_Y)

x_pred = np.array([[a value to predict]])
y_pred = svr.predict(x_pred)

print("Prediksi nilai Y untuk x = 4.146574 adalah:", y_pred[0])

"""# Bayesian Ridge Regression to predict CO2 conc. using CAMs or color spaces data"""

import numpy as np
from sklearn.linear_model import BayesianRidge
import matplotlib.pyplot as plt

x_train = np.array([series data of color spaces or CAMs values])

y_train = np.array([series data of experimental conc.])

x_train = x_train.reshape(-1, 1)

brr_model = BayesianRidge()

brr_model.fit(x_train, y_train)

x_new_predict = np.array([[a value to predict]])

y_pred = brr_model.predict(x_new_predict)

print("="*60)
print(f"X Value (Color/CAM) tested: {x_new_predict[0][0]}")
print(f"Predicted Concentration Value (Y) is: {y_pred[0]:.4f}")
print("="*60)

print(f"Regression Coefficient (W): {brr_model.coef_[0]:.4f}")
print(f"Intercept (b): {brr_model.intercept_:.4f}")

x_line = np.linspace(x_train.min(), x_train.max(), 100).reshape(-1, 1)
y_line = brr_model.predict(x_line)

plt.figure(figsize=(8, 6))
plt.scatter(x_train, y_train, color='blue', label='Calibration Data')
plt.plot(x_line, y_line, color='red', label='Bayesian Ridge Regression Model')
plt.scatter(x_new_predict, y_pred, color='green', marker='X', s=100, label='New Sample Prediction')

plt.title('Concentration Calibration vs. Color Data using Bayesian Ridge')
plt.xlabel('Color Space / CAMs Value (X)')
plt.ylabel('Experimental Concentration (Y)')
plt.legend()
plt.grid(True)
plt.show()

"""# KernelRidge (RBF) to predict CO2 conc. using CAMs or color spaces data"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import GridSearchCV, LeaveOneOut # GridSearchCV is used for optimization

x_train = np.array([series data of color spaces or CAMs values])

y_train = np.array([series data of experimental conc.])

x_train_2d = x_train.reshape(-1, 1)

param_grid = {
    'alpha': np.logspace(-3, 3, 7),
    'gamma': np.logspace(-3, 3, 7)
}

krr_base = KernelRidge(kernel='rbf')

grid_search = GridSearchCV(
    estimator=krr_base,
    param_grid=param_grid,
    scoring='neg_mean_squared_error',
    cv=5,
    verbose=0
)

print("Starting Grid Search for optimal KRR parameters...")
grid_search.fit(x_train_2d, y_train)
print("Grid Search complete.")

best_krr_model = grid_search.best_estimator_
best_params = grid_search.best_params_
best_score = grid_search.best_score_

x_new_predict = np.array([[a value to predict]])

y_pred = best_krr_model.predict(x_new_predict)

print("\n" + "="*60)
print("KERNEL RIDGE REGRESSION (RBF) RESULTS")
print("="*60)
print(f"Optimal Parameters Found: {best_params}")
print(f"Best Cross-Validation Score (Negative MSE): {best_score:.4f}")
print("-" * 60)
print(f"X Value Tested: {x_new_predict[0][0]}")
print(f"Predicted Concentration (Y) is: {y_pred[0]:.4f}")
print("="*60)

x_line = np.linspace(x_train.min(), x_train.max(), 100).reshape(-1, 1)
y_line = best_krr_model.predict(x_line)

plt.figure(figsize=(10, 7))
plt.scatter(x_train, y_train, color='blue', label='Calibration Data', marker='o')
plt.plot(x_line, y_line, color='red', label=f'Optimized KRR-RBF (alpha={best_params["alpha"]:.3f}, gamma={best_params["gamma"]:.3f})', linewidth=2)
plt.scatter(x_new_predict, y_pred, color='green', marker='X', s=150, label='New Sample Prediction', zorder=5)

plt.title('Concentration Calibration vs. Color Data: Optimized KRR-RBF')
plt.xlabel('Color Space / CAMs Value (X)')
plt.ylabel('Experimental Concentration (Y)')
plt.legend()
plt.grid(True)
plt.show()

"""# GaussianProcessRegressor (RBF + White) to predict CO2 conc. using CAMs or color spaces data"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel, ConstantKernel

x_train = np.array([series data of color spaces or CAMs values])

y_train = np.array([series data of experimental conc.])

x_train_2d = x_train.reshape(-1, 1)

kernel = ConstantKernel(1.0, (1e-3, 1e3)) * RBF(1.0, (1e-2, 1e2)) + WhiteKernel(1.0, (1e-5, 1e-1))

gpr_model = GaussianProcessRegressor(
    kernel=kernel,
    alpha=0.0,
    n_restarts_optimizer=10,
    random_state=42
)

print("Training Gaussian Process Regressor (GPR)...")
gpr_model.fit(x_train_2d, y_train)
print("Training complete.")

x_new_predict = np.array([[a value to predict]])

y_pred_mean, y_pred_std = gpr_model.predict(x_new_predict, return_std=True)

print("\n" + "="*70)
print("GAUSSIAN PROCESS REGRESSOR (RBF + WHITE) RESULTS")
print("="*70)
print(f"Optimized Kernel: {gpr_model.kernel_}")
print("-" * 70)
print(f"X Value Tested: {x_new_predict[0][0]}")
print(f"Predicted Concentration (Y mean): {y_pred_mean[0]:.4f}")
print(f"Prediction Uncertainty (Y std): ± {y_pred_std[0]:.4f}")
print("="*70)

x_line = np.linspace(x_train.min() - 0.5, x_train.max() + 0.5, 100).reshape(-1, 1)
y_line_mean, y_line_std = gpr_model.predict(x_line, return_std=True)

plt.figure(figsize=(10, 7))

plt.fill_between(
    x_line.ravel(),
    y_line_mean - 1.96 * y_line_std,
    y_line_mean + 1.96 * y_line_std,
    alpha=0.15,
    color='red',
    label='95% Confidence Interval'
)

plt.plot(x_line, y_line_mean, color='red', label='GPR Mean Prediction', linewidth=2)

plt.scatter(x_train, y_train, color='blue', label='Calibration Data', marker='o')
plt.errorbar(
    x_new_predict,
    y_pred_mean,
    yerr=y_pred_std,
    fmt='X',
    color='green',
    ecolor='green',
    capsize=5,
    markersize=10,
    label=f'New Prediction (Y={y_pred_mean[0]:.2f} ± {y_pred_std[0]:.2f})',
    zorder=5
)

plt.title('Concentration Calibration vs. Color Data: Gaussian Process Regression')
plt.xlabel('Color Space / CAMs Value (X)')
plt.ylabel('Experimental Concentration (Y)')
plt.legend()
plt.grid(True)
plt.show()

"""# Random Forest"""

import numpy as np
from sklearn.ensemble import RandomForestRegressor

data_x = np.array([series data of color spaces or CAMs values])
data_Y = np.array([series data of experimental conc.])

random_forest = RandomForestRegressor(n_estimators=100, random_state=42)

data_x = data_x.reshape(-1, 1)
random_forest.fit(data_x, data_Y)

x_pred = np.array([[a value to predict]])
y_pred = random_forest.predict(x_pred)

print("y value prediction for x = 72.28235294 is:", y_pred[0])

"""# RMSE, MAPE and R2 determination"""

import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

def mean_absolute_percentage_error(y_true, y_pred):
    """
    Calculate MAPE, ignoring instances where the true value is zero.

    Args:
    y_true (np.array): Array of true (real) values.
    y_pred (np.array): Array of predicted values.

    Returns:
    float: The MAPE value.
    """
    non_zero_indices = y_true != 0
    y_true_non_zero = y_true[non_zero_indices]
    y_pred_non_zero = y_pred[non_zero_indices]

    return np.mean(np.abs((y_true_non_zero - y_pred_non_zero) / y_true_non_zero)) * 100

def calculate_metrics(predicted, experimental):
    """
    Calculate MAPE, RMSE, and R² for the given predicted and experimental values.

    Args:
    predicted (np.array): Array of predicted values.
    experimental (np.array): Array of experimental (real) values.

    Returns:
    dict: A dictionary containing MAPE, RMSE, and R².
    """
    if len(predicted) != len(experimental):
        raise ValueError("Predicted and experimental arrays must have the same length.")

    metrics = {}
    metrics['MAPE'] = mean_absolute_percentage_error(experimental, predicted)
    metrics['RMSE'] = mean_squared_error(experimental, predicted, squared=False)
    metrics['R²'] = r2_score(experimental, predicted)

    return metrics

predicted = np.array([series of Predicted values])

experimental = np.array([series of Experimental (real) values])

metrics = calculate_metrics(predicted, experimental)

for metric, value in metrics.items():
    print(f"{metric}: {value:.4f}")

print("\nDetailed Results:")
print(f"Mean Absolute Percentage Error (MAPE): {metrics['MAPE']:.4f}")
print(f"Root Mean Squared Error (RMSE): {metrics['RMSE']:.4f}")
print(f"Coefficient of Determination (R²): {metrics['R²']:.4f}")

"""# LOD determination"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

Specific component of color spaces or CAMs = [series of CAMs/color spaces values]
CO2 = [series of CO2 experimental conc.]

data = pd.DataFrame({
    'R_of_ACES_AP0': R_of_ACES_AP0,
    'CO2': CO2
})

X = data['R_of_ACES_AP0'].values.reshape(-1, 1)
y = data['CO2'].values

model = LinearRegression()
model.fit(X, y)

predictions = model.predict(X)
residuals = y - predictions

std_residuals = np.std(residuals)

slope = model.coef_[0]

LOD = 3 * std_residuals / slope

print(f'Slope of calibration curve: {slope}')
print(f'Standard deviation of residuals: {std_residuals}')
print(f'Limit of Detection (LOD): {LOD}')

plt.scatter(X, y, label='Data')
plt.plot(X, predictions, color='red', label='Linear fit')
plt.xlabel('R of ACES AP0')
plt.ylabel('CO2 (%)')
plt.legend()
plt.show()